name: PullRequest

on: [pull_request]

jobs:
  buildMod:
    name: build mod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: build mod
        run:  ./gradlew build
      - name: grab artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: RTS mod
          path: build/libs/*.jar
  prepareClient:
    name: prepare client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: prepare client
        run:  ./gradlew prepareRunClient
  prepareServer:
    name: prepare server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: prepare server
        run:  ./gradlew prepareRunServer
  prepareData:
    name: prepare Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: prepare Data
        run:  ./gradlew prepareRunData